// This file is generated by the rs-update-tests script

#include "rs-unit-test.hpp"

int main(int argc, char** argv) {

    RS::UnitTest::begin_tests(argc, argv);

    // version-test.cpp
    UNIT_TEST(rs_graphics_core_version)

    // maths-test.cpp
    UNIT_TEST(rs_graphics_core_maths_rounding)
    UNIT_TEST(rs_graphics_core_maths_euclidean_division)
    UNIT_TEST(rs_graphics_core_maths_fraction)
    UNIT_TEST(rs_graphics_core_maths_interpolate)
    UNIT_TEST(rs_graphics_core_maths_symmetric_division)
    UNIT_TEST(rs_graphics_core_maths_numeric_literals)

    // root-finding-test.cpp
    UNIT_TEST(rs_graphics_core_root_finding_newton_raphson)

    // linear-map-test.cpp
    UNIT_TEST(rs_graphics_core_linear_map)

    // vector-test.cpp
    UNIT_TEST(rs_graphics_core_integer_vector_construction)
    UNIT_TEST(rs_graphics_core_integer_vector_arithmetic)
    UNIT_TEST(rs_graphics_core_integer_vector_hash)
    UNIT_TEST(rs_graphics_core_integer_vector_total_order)
    UNIT_TEST(rs_graphics_core_floating_vector_construction)
    UNIT_TEST(rs_graphics_core_floating_vector_arithmetic)

    // multi-array-test.cpp
    UNIT_TEST(rs_graphics_core_multi_array_2d)
    UNIT_TEST(rs_graphics_core_multi_array_3d)

    // matrix-test.cpp
    UNIT_TEST(rs_graphics_core_matrix_basics)
    UNIT_TEST(rs_graphics_core_matrix_inversion)

    // quaternion-test.cpp
    UNIT_TEST(rs_graphics_core_quaternion)

    // transform-test.cpp
    UNIT_TEST(rs_graphics_core_2d_transforms)
    UNIT_TEST(rs_graphics_core_3d_transforms)
    UNIT_TEST(rs_graphics_core_projective_geometry)
    UNIT_TEST(rs_graphics_core_primitive_transforms)
    UNIT_TEST(rs_graphics_core_quaternion_transforms)

    // geometry-test.cpp
    UNIT_TEST(rs_graphics_core_geometry_box)
    UNIT_TEST(rs_graphics_core_geometry_sphere)

    // colour-space-test.cpp
    UNIT_TEST(rs_graphics_core_colour_space_ciexyy)
    UNIT_TEST(rs_graphics_core_colour_space_cielab)
    UNIT_TEST(rs_graphics_core_colour_space_cieluv)
    UNIT_TEST(rs_graphics_core_colour_space_srgb)
    UNIT_TEST(rs_graphics_core_colour_space_adobe_rgb)
    UNIT_TEST(rs_graphics_core_colour_space_pro_photo)
    UNIT_TEST(rs_graphics_core_colour_space_wide_gamut)
    UNIT_TEST(rs_graphics_core_colour_space_hsl)
    UNIT_TEST(rs_graphics_core_colour_space_hsv)
    UNIT_TEST(rs_graphics_core_colour_space_conversion)

    // colour-test.cpp
    UNIT_TEST(rs_graphics_core_colour_floating_point_elements)
    UNIT_TEST(rs_graphics_core_colour_floating_point_arithmetic)
    UNIT_TEST(rs_graphics_core_colour_floating_point_standard_colours)
    UNIT_TEST(rs_graphics_core_colour_integral_elements)
    UNIT_TEST(rs_graphics_core_colour_integral_standard_colours)
    UNIT_TEST(rs_graphics_core_colour_integral_arithmetic)
    UNIT_TEST(rs_graphics_core_colour_channel_order)
    UNIT_TEST(rs_graphics_core_colour_premultiplied_alpha)
    UNIT_TEST(rs_graphics_core_colour_conversion_between_colour_spaces)
    UNIT_TEST(rs_graphics_core_colour_conversion_between_representations)
    UNIT_TEST(rs_graphics_core_colour_hex_representation)
    UNIT_TEST(rs_graphics_core_colour_alpha_blending)

    // noise-test.cpp
    UNIT_TEST(rs_graphics_core_noise_result_stability)
    UNIT_TEST(rs_graphics_core_noise_multiple_sources)
    UNIT_TEST(rs_graphics_core_noise_statistics)
    UNIT_TEST(rs_graphics_core_noise_sample_renders)

    // unit-test.cpp

    return RS::UnitTest::end_tests();

}
